PROGRAM PRG_PneumaticValve_Control
VAR_INPUT
	Pne_Valve_YV1 : BOOL; // 气动电磁阀YV1
	Pne_Valve_YV2 : BOOL; // 气动电磁阀YV2
	Pne_Valve_YV3 : BOOL; // 气动电磁阀YV3
	Pne_Valve_YV4 : BOOL; // 气动电磁阀YV4
	Pne_Valve_YV5 : BOOL; // 气动电磁阀YV5
	Pne_Valve_YV6 : BOOL; // 气动电磁阀YV6
	Pne_Valve_YV7 : BOOL; // 气动电磁阀YV7
	Pne_Valve_YV8 : BOOL; // 气动电磁阀YV8
	Pne_Valve_YV9 : BOOL; // 气动电磁阀YV9
	Pne_Valve_YV10 : BOOL; // 气动电磁阀YV10
	Pne_Valve_YV11 : BOOL; // 气动电磁阀YV11
	Pne_Valve_YV12 : BOOL; // 气动电磁阀YV12
	Pne_Valve_YV13 : BOOL; // 气动电磁阀YV13
END_VAR
END_PROGRAM
